#pragma once
#include "NativeGameplayTags.h"

//namespace NOS_GameplayTags
//{
//}

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TipType_Common);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TipType_Queue);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TipType_SingleOverride);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layout_Root);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layout_SeparatelyShow);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layout_PanelShow);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layout_Bot);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layout_Mid);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layout_Top);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layout_System);